function Bent2dCreateFORCMagnetosomeScripts(x,y,z,d,N,b)
% Bent2dCreateFORCMagnetosomeScripts(40,40,40,8,10,0)
    path = 'mesh_bent2d_FORC';
    domainpath = 'domainstates_bent2d_FORC';
    merrillpath = 'D:/magnetosomes';
    scriptpath = 'D:/magnetosomes/scripts/hysteresis_bent2d_FORC';
    hystpath = 'hysteresis_bent2d_FORC';
    filename = sprintf('2d_FORC_%dx_%dy_%dz_%dd_%dN_%db', x, y, z, d, N, b);
    [~,~,~] = mkdir(sprintf('%s/%s', merrillpath, domainpath), filename);
    [~,~,~] = mkdir(sprintf('%s/%s', merrillpath, hystpath));
    [~,~,~] = mkdir(sprintf('%s',scriptpath));
    meshname = sprintf('%s/magnetosome2d_FORC_%dx_%dy_%dz_%dd_%dN_%db',path,x,y,z,d,N,b);

    for i=1:20
        fid = fopen(sprintf('%s/%s_model%d.script',scriptpath,filename,i),'w');
        fprintf(fid,[...
            'magnetite 20 C'                                              '\r\n'...
            'external field direction 1 0 0'                              '\r\n'...
            'external field strength 0 mT'                                '\r\n'...
            'set MaxmeshNumber 2'                                         '\r\n'...
            'ReadMesh 1 %s_model%d.pat'                                      '\r\n'...
            'set MaxEnergyEvaluations 5000'                             '\r\n'...
            'uniform magnetization 1 0 0'                                 '\r\n'...
            ],meshname,i);
        anisfilename = sprintf('D:/magnetosomes/cubit_bent2d_FORC/Anis_magnetosome%s_model%d.txt',filename,i);
        anistxt = textread(anisfilename,'%s','delimiter', '\r');
        for j=1:150
            fprintf(fid,'%s \r',char(anistxt(j)));
        end
        fprintf(fid,[...
            'Loop field 200 -200 -5'                                      '\r\n'...
            '    external field strength %%field mT '                          '\r\n'...
            '    randomize magnetization 10'                                  '\r\n'...
            '    Minimize'                                                    '\r\n'...
            '    WriteMagnetization %s/%s/%s_model%d_hyst_$field$mT'     '\r\n'...
            '    WriteHyst %s/%s_model%d_hyst'               '\r\n'...
            'EndLoop'                                                     '\r\n'...
            ],domainpath,filename,filename,i,hystpath,filename,i);
        for a=200:-5:-200
            fprintf(fid,[...
                'ReadMagnetization %s/%s/%s_model%d_hyst_%dmT.dat'        '\r\n'...
                'Loop field %d 200 5'                                       '\r\n'...
                '    external field strength %%field mT'                        '\r\n'...
                '    randomize magnetization 10'                                '\r\n'...
                '    Minimize '                                                 '\r\n'...
                '    WriteHyst %s/%s_model%d_%dmT'                       '\r\n'...
                'EndLoop'                                                   '\r\n'...
                ],domainpath,filename,filename,i,a,a,hystpath,filename,i,a);
        end
        fclose(fid);
    end
end